import { createElement } from 'lwc';
import CodinDay2ChallengeJSFunctins from 'c/codinDay2ChallengeJSFunctins';

describe('c-codin-day2-challenge-js-functins', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-codin-day2-challenge-js-functins', {
            is: CodinDay2ChallengeJSFunctins
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});